instructions_to_count:
- mul
# - div
- add
- sub
- fmul
- fdiv
- fadd
- fsub
- fma
- or
- and
- load
- store
- getelementptr
- icmp
- br
- llvm.fmuladd.f32
- shared_load
- shared_store
- __nv_sinf
- __nv_sin
- __nv_cosf
- __nv_cos
- __hadd
- __hsub
- llvm.nvvm.fma.rn.d
- llvm.nvvm.mul.rn.d
- llvm.nvvm.sqrt.rn.d
energy_model_names: [all_ones]
targets_allowed: [gpu]
aggregation_level: all
verbose: false
run_tests: false
